program.exe: main.cc	auxiliars.cc RGG_generator.cc components.cc percolacio_Grafs.cc NxN_Generator.cc
	g++	-o	program.exe	main.cc	auxiliars.cc RGG_generator.cc components.cc percolacio_Grafs.cc	NxN_Generator.cc


clean:
	rm *.exe
